name: Deploy Master to Yandex Serverless Containers

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build the Docker image
        run: docker build --progress=plain --no-cache --tag cr.yandex/crp8hjr4pmger3bekt96/tf-diamonds-dev:${{ github.sha }} .
      - name: Docker Push
        run: docker push cr.yandex/crp8hjr4pmger3bekt96/tf-diamonds-dev:${{ github.sha }}
